apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dados-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: luizmachado/desafio5_database:1.0
        args:
        - "--ignore-db-dir=lost+found"
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-dados
        persistentVolumeClaim:
          claimName: mysql-dados-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: luizmachado/desafio5_backend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
